version: "3.6"

services:
  # postgres database
  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
  wca:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wca
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes:
  #     - cache:/data
volumes:
  cache:
    driver: local
